Review project from trials
butlermuwo/project-from-trials pull request #1
Opened 2021-11-29 21:21 UTC by butlermuwo

## Review project from trials
In this code I was reviewing a project I did during the trials. 

- it is always advisable to put the `script` file just before the `body` closing tag. [Make reference here](https://github.com/butlermuwo/project-from-trials/blob/b0101704cabb80a84bc1c08b137c34299cd5c562/index.html#L10)
- It's good practice to add the viewpoint for responsive web design in the `head` tag. [Make reference here] (https://github.com/butlermuwo/project-from-trials/blob/b0101704cabb80a84bc1c08b137c34299cd5c562/index.html#L3)
- It is advisable to add the `alt` attribute inside your `image` tag for accessibility purposes, allowing for a user to get a full description of the `image` in an event the `image` doesn't load. [Make reference here] (https://github.com/butlermuwo/project-from-trials/blob/b0101704cabb80a84bc1c08b137c34299cd5c562/index.html#L12)
- frameBorder="0" is obsolete and it's best practice to use CSS instead  😃. [Make reference here] (https://github.com/butlermuwo/project-from-trials/blob/b0101704cabb80a84bc1c08b137c34299cd5c562/index.html#L25)
- There is a duplicate of `border` in this property, it best practice not to duplicate values.  [Make reference  here] (https://github.com/butlermuwo/project-from-trials/blob/b0101704cabb80a84bc1c08b137c34299cd5c562/css/style.css#L60)

2021-11-29 21:50 UTC, Gambit142 requested changes
Hi @butlermuwo , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️

- [ ] Kindly use inline comments for your review. An inline comment is a feature in GitHub that allows reviewers to bring an author's attention to some specific lines of codes that require changes. You can read more on inline comments in this [article](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-29 22:31 UTC, butlermuwo reviewed
- Changes to be made ♻️

2021-11-29 22:31 UTC, butlermuwo commented on css/style.css
> -  border: none;
- There is a duplicate of `border` in this property, it best practice not to duplicate values. There is a duplicate of `border` in this property, it best practice not to duplicate values.

2021-11-29 22:31 UTC, butlermuwo commented on index.html
> +    <title>Fork Me FCC: Test Suite Template</title>
- It's good practice to add the viewpoint for responsive web design across different devices in the `head` tag. 😃

2021-11-29 22:31 UTC, butlermuwo commented on index.html
> -
- It is advisable to remove all blank lines without any code, use extensions in your code editor to help you with formatting lines of code, for easy work efficiency. 👍

2021-11-29 22:31 UTC, butlermuwo commented on index.html
> +        src="https://cdn.freecodecamp.org/testable-projects-fcc/images/product-landing-page-logo.png" alt=""
- It is a requirement to add the alt attribute inside your `image` tag for accessibility purposes, allowing a user to get a full description of the `image` in an event that the `image` doesn't load.

2021-11-29 22:31 UTC, butlermuwo commented on index.html
> -      frameborder="0"
- frameBorder="0" is obsolete and it's best practice to use `CSS` instead. 😃

2021-11-29 22:47 UTC, brytebee approved these changes
Hi @butlermuwo 👋,

# STATUS: APPROVED 🕺🥳 

Congratulations🍾🥳!! Your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

![](https://media.giphy.com/media/3o6fIUZTTDl0IDjbZS/giphy.gif)

Good luck! 🎉 

- [x] **Optional** Always add your node modules to the `.gitignore` file. Leaving the node module is unprofessional and negates clean code. 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-29 23:37 UTC, brytebee approved these changes
Hi @butlermuwo 👋,

# STATUS: APPROVED 🕺🥳 

Congratulations🍾🥳!! Your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

![](https://media.giphy.com/media/l49JNZ87F3AmPoH0A/giphy.gif)

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-07 08:58 UTC, closed without merging

2021-12-07 08:59 UTC, butlermuwo commented
- closed pull request.